### ISSUE TITLE
Btrace 2.0 fails to re-instrument 

### ISSUE THREAD

**Issue by ivenhov** [btraceio/btrace#406] opened 2020-03-01 11:23 UTC
Hi

I have a problem where I start btrace like
sudo ./bin/btrace 12345~/btrace-scripts/AllCallsByteBuffers.java

This works OK but only on first launch.
Once I exit with option 1 and re-launch it in exact the same way I don't see instrumentation working.

This does not seems to be a problem with previous version of btrace.
Adjusted script to work on old version (I think 1.3 or similar) works every time, no matter how many times btrace is re-launched
Is this a known issue or am I doing something wrong?

Version 2.0 of the script below

```
package samples;

import org.openjdk.btrace.core.annotations.BTrace;
import org.openjdk.btrace.core.annotations.Kind;
import org.openjdk.btrace.core.annotations.Location;
import org.openjdk.btrace.core.annotations.OnMethod;
import org.openjdk.btrace.core.annotations.ProbeMethodName;
import org.openjdk.btrace.core.annotations.Self;
import org.openjdk.btrace.core.annotations.ProbeClassName;
import org.openjdk.btrace.core.annotations.ProbeMethodName;

import static org.openjdk.btrace.core.BTraceUtils.*;

@BTrace public class AllCallsByteBuffers20 {
    @OnMethod(
        clazz="/com\\.a\\.b\\.c\\.ByteBuffers/",
        method="/.*/"
    )
    public static void enterMethodOfByteBuffers(@ProbeClassName String probeClass, @ProbeMethodName String probeMethod) {
        print(Strings.strcat("\nEntered ", probeClass));
        print(Strings.strcat(Strings.strcat(".", probeMethod), "()"));
        println(Strings.strcat(" at ",timestamp("yyyy-MM-dd HH:mm:ss.SSS")));
        jstack();
    }
}
```

**Comment by scutlxp** [comment] 2020-03-19 02:18
I have the same problem with Btrace 2.0，When I use -v flag, I found the error shown below
```java
java.util.concurrent.ExecutionException: java.lang.ClassFormatError
   at java.util.concurrent.FutureTask.report(FutureTask.java:122)
   at java.util.concurrent.FutureTask.get(FutureTask.java:192)
   at org.openjdk.btrace.agent.Main.startServer(Main.java:747)
   at org.openjdk.btrace.agent.Main.access$000(Main.java:71)
   at org.openjdk.btrace.agent.Main$2.run(Main.java:136)
   at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassFormatError
   at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
   at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
   at org.openjdk.btrace.agent.Client.retransformLoaded(Client.java:476)
   at org.openjdk.btrace.agent.Main$5.run(Main.java:766)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutrueTask.run(FutureTask.java:266)
   ... 3 more
```

**Comment by scutlxp** [comment] 2020-03-19 10:37
By outputting the bytecode, I found that the first n-1 trace methods will be re-injected into the target jvm at the n-th trace as follows:
```java
// Omit target class code
// ......

private static void $btrace$org$openjdk$btrace$runtime$aux$Test$trace(String var0) {}
private static void $btrace$org$openjdk$btrace$runtime$aux$Test$1$trace(String var0) {}
private static void $btrace$org$openjdk$btrace$runtime$aux$Test$2$trace(String var0) {}

@OnMethod(
   clazz = "TestMain",
   method = "/.*/"
)
private static void $btrace$org$openjdk$btrace$runtime$aux$Test$3$trace(@ProbeMethodName String var0) {
   if (BTraceRuntimeAccess.enter(3.runtime)) {
      try {
         BTraceUtils.println(var0);
         3.runtime.leave();
      } catch (Throwable var1) {
         3.runtime.handleException(var1);
         3.runtime.leave();
      }
   }
}
```
This is not the same as v1.3，I suspect this is the cause of the ClassFormatError.  By comparing with v1.3, modify the `instrument` method in `org.openjdk.btrace.instr.BTraceClassWriter` as follows:
```java
public byte[] instrument() {
        boolean hit = false;
        synchronized (instrumentors) {
            if (instrumentors.isEmpty()) return null;

            ClassVisitor top = instrumentors.peekLast();
            //ClassVisitor cv = new ClassVisitor(Opcodes.ASM7, top != null ? top : this) {
            //    private String cname;
            //    @Override
           //     public void visit(int version, int access, String name, String signature, String superName, String[] interfaces) {
            //        cname = name;
            //        super.visit(version, access, name, signature, superName, interfaces);
             //   }
             // @Override
             //   public void visitEnd() {
               //     for (MethodNode m : cushionMethods) {
                //        m.accept(this);
                //    }
                //    super.visitEnd();
            //    }
         //   };
            InstrumentUtils.accept(cr, top != null ? top : this);
            for (Instrumentor i : instrumentors) {
                hit |= i.hasMatch();
            }
        }
        return hit ? toByteArray() : null;
    }
```
Then it can re-instrument success. But due to the lack of learning about ASM, I still don't understand why this change can take effect and whether it will bring other errors.

**Comment by jbachorik** [comment] 2020-03-19 13:12
Hi @scutlxp - nice analysis, thanks!
If the code is correctly interpreted by GitHub then the culprit is `BTraceRuntimeAccess.enter(3.runtime)` - and namely `3.runtime`. It is not a valid identifier and it should not be there.

In fact, the method bodies of 'dead' instrumentation should be empty. We just need to keep the method around for code which hasn't managed to replace the bytecode calling the dead instrumentation eg. because of being in a hot loop.

**Comment by scutlxp** [comment] 2020-03-20 02:31
I noticed that you mentioned 'hot loop'. I guess that was to resolve the `java.lang.NoSuchMethodError` in [#344](https://github.com/btraceio/btrace/issues/344). But from my actual use, v2.0 did not solve the error. Here is my analysis：

The target class code as follows:
```java
public class TestMain {
   public static void main(String[] args) throws InterruptedException {
      while(true) {
         print("hello btrace");
      }
   }
   private static void print(String message) throws InterruptedException { 
     Thread.sleep(100);
      System.out.println(message);
   }
}
```
The btrace script is:
```java
@BTrace
public class Test {
   @OnMethod(
      clazz = "TestMain",
      method = "print",
      location = @Location(Kind.RETURN)
   )
   public static void trace (@Duration long time) {
      println(time);
   }
}
```
The print bytecode is as follows：
```java
public class TestMain {
   private static void $btrace$org$openjdk$btrace$runtime$aux$Test$trace(long var0) {
      if (BTraceRuntimeAccess.enter(Test.runtime)) {
         try {
            BTraceUtils.println(var0);
            Test.runtime.leave();
         } catch (Throwable var2) {
            Test.runtime.handleException(var2);
            Test.runtime.leave();
         }
      }
   }

   public TestMain() {}

   public static void main(String[] args) throws InterruptedException {
      while(true) {
         print("hello btrace");
      }
   }

   private static void print (String message) throws InterruptedException {
      long var1 = 0L;
      long var3 = System.nanoTime();
      Thread.sleep(100L);
      System.out.println(message);
      var1 = System.nanoTime() - var3;
      $btrace$org$openjdk$btrace$runtime$aux$Test$trace(var1);
   }
}
```
I think the reason for java.lang.NoSuchMethodError is that when exiting (ctrl + c), the trace method bytecode will be remove. Refer to the JDK documentation，if a retransformed method has active stack frames, those active frames continue to run the bytecodes of the original method. The retransformed method will be used on new invokes. So the traced method (`print`) do nothing because it is in sleep (or other blocking call). When it wakes up, it will call the trace method that has been cleared, which caused `java.lang.NoSuchMethodError`. That's why this error only happens with `@RETURN` and `@CALL` (with Where.AFTER）

Keeping the 'dead' method doesn't work, because it is also cleared when exit btrace client.
One of my solutions was to use a try catch clause to wrap the trace method call:
```java
private static void print (String message) throws InterruptedException {
      long var1 = 0L;
      long var3 = System.nanoTime();
      Thread.sleep(100L);
      System.out.println(message);
      var1 = System.nanoTime() - var3;
      try {
         $btrace$org$openjdk$btrace$runtime$aux$Test$trace(var1);
      } catch (Throwable t) {
      }
   }
```

**Comment by scutlxp** [comment] 2020-03-20 03:08
Corrected, the same problem may occur in `@CALL` with `Where.BEFORE`

**Comment by jbachorik** [comment] 2020-03-22 16:16
Indeed. And that is supposed to be fixed by keeping empty-bodied versions of handler methods from previous instrumentations around - such that the method resolution will not fail in cases you are describing.

**Comment by jbachorik** [comment] 2020-03-22 16:54
Ok, I see now - the pseudo code reported by @scutlxp is missing the package and parent class information.
Here is what I am seeing when doing `javap`
```
private static void $btrace$org$openjdk$btrace$runtime$aux$AllMethods1$1$m(java.lang.Object, java.lang.String, java.lang.String);
    descriptor: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
    flags: (0x000a) ACC_PRIVATE, ACC_STATIC
    Code:
      stack=3, locals=3, args_size=3
         0: getstatic     #2150               // Field org/openjdk/btrace/runtime/aux/AllMethods1$1.runtime:Lorg/openjdk/btrace/runtime/BTraceRuntimeImplBase;
         3: invokestatic  #2156               // Method org/openjdk/btrace/runtime/BTraceRuntimeAccess.enter:(Lorg/openjdk/btrace/core/BTraceRuntime$Impl;)Z
         6: ifne          10
         9: return
        10: new           #491                // class java/lang/StringBuilder
        13: dup
        14: invokespecial #2157               // Method java/lang/StringBuilder."<init>":()V
        17: ldc_w         #2159               // String this =
        20: invokevirtual #2163               // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        23: aload_0
        24: invokevirtual #2166               // Method java/lang/StringBuilder.append:(Ljava/lang/Object;)Ljava/lang/StringBuilder;
        27: invokevirtual #2167               // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
        30: invokestatic  #2172               // Method org/openjdk/btrace/core/BTraceUtils.println:(Ljava/lang/Object;)V
        33: new           #491                // class java/lang/StringBuilder
        36: dup
        37: invokespecial #2157               // Method java/lang/StringBuilder."<init>":()V
        40: ldc_w         #2174               // String entered
        43: invokevirtual #2163               // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        46: aload_1
        47: invokevirtual #2163               // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        50: invokevirtual #2167               // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
        53: invokestatic  #2176               // Method org/openjdk/btrace/core/BTraceUtils.print:(Ljava/lang/Object;)V
        56: new           #491                // class java/lang/StringBuilder
        59: dup
        60: invokespecial #2157               // Method java/lang/StringBuilder."<init>":()V
        63: ldc_w         #2178               // String .
        66: invokevirtual #2163               // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        69: aload_2
        70: invokevirtual #2163               // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        73: invokevirtual #2167               // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
        76: invokestatic  #2172               // Method org/openjdk/btrace/core/BTraceUtils.println:(Ljava/lang/Object;)V
        79: getstatic     #2150               // Field org/openjdk/btrace/runtime/aux/AllMethods1$1.runtime:Lorg/openjdk/btrace/runtime/BTraceRuntimeImplBase;
        82: invokevirtual #2183               // Method org/openjdk/btrace/runtime/BTraceRuntimeImplBase.leave:()V
        85: return
        86: getstatic     #2150               // Field org/openjdk/btrace/runtime/aux/AllMethods1$1.runtime:Lorg/openjdk/btrace/runtime/BTraceRuntimeImplBase;
        89: dup_x1
        90: swap
        91: invokevirtual #2187               // Method org/openjdk/btrace/runtime/BTraceRuntimeImplBase.handleException:(Ljava/lang/Throwable;)V
        94: getstatic     #2150               // Field org/openjdk/btrace/runtime/aux/AllMethods1$1.runtime:Lorg/openjdk/btrace/runtime/BTraceRuntimeImplBase;
        97: invokevirtual #2183               // Method org/openjdk/btrace/runtime/BTraceRuntimeImplBase.leave:()V
       100: return
      Exception table:
         from    to  target type
            10    86    86   Class java/lang/Throwable
      StackMapTable: number_of_entries = 2
        frame_type = 10 /* same */
        frame_type = 247 /* same_locals_1_stack_item_frame_extended */
          offset_delta = 75
          stack = [ class java/lang/Throwable ]
    RuntimeVisibleAnnotations:
      0: #2137(#2138=s#2139,#2140=s#2141)
        org.openjdk.btrace.core.annotations.OnMethod(
          clazz="/javax\\.swing\\..*/"
          method="/.*/"
        )
    RuntimeVisibleParameterAnnotations:
      parameter 0:
        0: #2142()
          org.openjdk.btrace.core.annotations.Self
      parameter 1:
        0: #2143()
          org.openjdk.btrace.core.annotations.ProbeClassName
      parameter 2:
        0: #2144()
          org.openjdk.btrace.core.annotations.ProbeMethodName
}
```

I have verified that this bytecode is generated correctly regardless of how many disconnect/reattach iterations. 

Can any of you, @ivenhov or @scutlxp run btrace with `-d <path to dump classes>` and then either send me the classes from that directory (if they are not confidential) or run `org.objectweb.asm.util.CheckClassAdapter` on them to see a better verification report. This class is a part of asm-util package but the easiest start would be downloading [asm-all](https://repository.ow2.org/nexus/content/repositories/releases/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar) and then running `java -cp asm-all-5.2.jar org.objectweb.asm.util.CheckClassAdapter <class to check>` and post the check results.

Thanks in advance for cooperation.

**Comment by scutlxp** [comment] 2020-03-23 02:13
OK, I did as you said, here is the analysis result of the class file after the second attach
```
$ java -cp asm-all-5.2.jar org.objectweb.asm.util.CheckClassAdapter TestMain.class
org.objectweb.asm.tree.analysis.AnalyzerException: Execution can fall off end of the code
        at org.objectweb.asm.tree.analysis.Analyzer.findSubroutine(Unknown Source)
        at org.objectweb.asm.tree.analysis.Analyzer.analyze(Unknown Source)
        at org.objectweb.asm.util.CheckClassAdapter.verify(Unknown Source)
        at org.objectweb.asm.util.CheckClassAdapter.verify(Unknown Source)
        at org.objectweb.asm.util.CheckClassAdapter.main(Unknown Source)
$btrace$org$openjdk$btrace$runtime$aux$Test$trace(Ljava/lang/String;)V

org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 1: java.lang.ClassNotFoundException: org.openjdk.btrace.core.BTraceRuntime$Impl
        at org.objectweb.asm.tree.analysis.Analyzer.analyze(Unknown Source)
        at org.objectweb.asm.util.CheckClassAdapter.verify(Unknown Source)
        at org.objectweb.asm.util.CheckClassAdapter.verify(Unknown Source)
        at org.objectweb.asm.util.CheckClassAdapter.main(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.openjdk.btrace.core.BTraceRuntime$Impl
        at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(Unknown Source)
        at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(Unknown Source)
        at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(Unknown Source)
        at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(Unknown Source)
        at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(Unknown Source)
        at org.objectweb.asm.tree.analysis.Frame.execute(Unknown Source)
        ... 4 more
$btrace$org$openjdk$btrace$runtime$aux$Test$1$trace(Ljava/lang/String;)V
00000 String  :  :     GETSTATIC org/openjdk/btrace/runtime/aux/Test$1.runtime : Lorg/openjdk/btrace/runtime/BTraceRuntimeImplBase;
00001 String  : BTraceRuntimeImplBase  :     INVOKESTATIC org/openjdk/btrace/runtime/BTraceRuntimeAccess.enter (Lorg/openjdk/btrace/core/BTraceRuntime$Impl;)Z
00002 ?     :     IFNE L0
00003 ?     :     RETURN
00004 ?     :    L0
00005 ?     :    FRAME SAME
00006 ?     :     ALOAD 0
00007 ?     :     INVOKESTATIC org/openjdk/btrace/core/BTraceUtils.println (Ljava/lang/Object;)V
00008 ?     :     GETSTATIC org/openjdk/btrace/runtime/aux/Test$1.runtime : Lorg/openjdk/btrace/runtime/BTraceRuntimeImplBase;
00009 ?     :     INVOKEVIRTUAL org/openjdk/btrace/runtime/BTraceRuntimeImplBase.leave ()V
00010 ?     :     RETURN
00011 ?     :    L1
00012 ?     :    FRAME SAME1 java/lang/Throwable
00013 ?     :     GETSTATIC org/openjdk/btrace/runtime/aux/Test$1.runtime : Lorg/openjdk/btrace/runtime/BTraceRuntimeImplBase;
00014 ?     :     DUP_X1
00015 ?     :     SWAP
00016 ?     :     INVOKEVIRTUAL org/openjdk/btrace/runtime/BTraceRuntimeImplBase.handleException (Ljava/lang/Throwable;)V
00017 ?     :     GETSTATIC org/openjdk/btrace/runtime/aux/Test$1.runtime : Lorg/openjdk/btrace/runtime/BTraceRuntimeImplBase;
00018 ?     :     INVOKEVIRTUAL org/openjdk/btrace/runtime/BTraceRuntimeImplBase.leave ()V
00019 ?     :     RETURN
     TRYCATCHBLOCK L0 L1 L1 java/lang/Throwable
```

The `classfile.zip` folder contains three files, `Test.java` is the BTrace script, `TestMain.java` is the target program, and `TestMain.class` is obtained with the `-d ` option
[classfile.zip](https://github.com/btraceio/btrace/files/4366884/classfile.zip)

**Comment by jbachorik** [comment] 2020-03-23 09:41
Thanks, I will take a look during this week.

**Comment by jbachorik** [comment] 2020-03-29 13:05
The cushion methods were not properly adding `RETURN` instruction, rendering the bytecode invalid.
Unfortunately, this validation is triggered only *if* that method is invoked - eg. the bytecode containing invocation of the previous instrumentation has not been replaced yet.
Thanks for reporting this again. The issue is fixed in develop branch.

**Closed** 2020-04-19 20:31 UTC
Labels: Core, regression
