### ISSUE TITLE
NoClassDefFoundError TaskListener

### ISSUE THREAD

**Issue by spiderqn** [btraceio/btrace#418] opened 2020-05-03 02:12 UTC
/usr/local/btrace/bin/btrace -cp /usr/local/btrace/libs 5366 BTraceTests.java
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/source/util/TaskListener
        at org.openjdk.btrace.compiler.Compiler.<init>(Compiler.java:70)
        at org.openjdk.btrace.compiler.Compiler.<init>(Compiler.java:74)
        at org.openjdk.btrace.client.Client.compile(Client.java:204)
        at org.openjdk.btrace.client.Client.compile(Client.java:187)
        at org.openjdk.btrace.client.Main.main(Main.java:195)
Caused by: java.lang.ClassNotFoundException: com.sun.source.util.TaskListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more

**Comment by spiderqn** [comment] 2020-05-03 02:14
# echo $JAVA_HOME
/usr/local/jdk1.8.0_221
# echo $BTRACE_HOME
/usr/local/btrace
# btrace --version
BTrace v.2.0.0 (15dcb82b539b4c6fab72b01da8ead18a5b8f71a0)
# java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

**Comment by jbachorik** [comment] 2020-05-24 08:53
Duplicate of #415

**Closed by jbachorik** 2020-05-24 08:53 UTC
