### ISSUE TITLE
BTrace is crashing the applications that is attached with

### ISSUE THREAD

**Issue by AbhishekPuligundla** [btraceio/btrace#181] opened 2015-11-03 06:25 UTC
Even if i am using the jdk of the application it is still crashing.

i am getting an error 
java.lang.reflect.InvocationTargetException 

caused by
 java.lang.VerifyError

**Comment by jbachorik** [comment] 2015-11-03 07:28
This is a different mode of failure. Does the application actually crash or is it just BTrace?
Anything interesting in the application log?

If you are attaching dynamically use `btrace -v -d <dump_class_dir> ...`  to get more verbose output from BTrace and also to dump the instrumented classes into 'dump_class_dir'. When you have this debug info ready, please, zip it and attach the archive here.

**Comment by AbhishekPuligundla** [comment] 2015-11-03 12:14
DEBUG: accepting port 2020
DEBUG: dumpDir is c:\Users\Administrator\Desktop\
DEBUG: assuming default classpath '.'
DEBUG: compiling TraceExample.java
DEBUG: compiled TraceExample.java
DEBUG: attaching to 3396
DEBUG: checking port availability: 2020
DEBUG: attached to 3396
DEBUG: loading C:\Users\Administrator\Desktop\btracebin\build\btrace-agent.jar
DEBUG: agent args: port=2020,statsd=,debug=true,dumpClasses=true,dumpDir=c:\Users\Administrator\Desktop\,systemClassPath=C:\myApplication\Java\jd
k\jre/../lib/tools.jar,probeDescPath=.
DEBUG: loaded C:\Users\Administrator\Desktop\btracebin\build\btrace-agent.jar
DEBUG: registering shutdown hook
DEBUG: registering signal handler for SIGINT
DEBUG: submitting the BTrace program
DEBUG: opening socket to 2020
DEBUG: sending instrument command
DEBUG: entering into command loop
DEBUG: received com.sun.btrace.comm.OkayCommand@b4cef0






it isn't proceeding after it. some times one or two more lines similar to the last line will be added and that's all after that nothing will happen. And during that time when i try to work with the application it is    not working properly. Even the dump files are created, since i think instrumentation is not started.

the log file contains the error i mentioned above and apart from that nothing interesting is happening.


i have a doubt can btrace trace applications that are connected with a database. i think it might be the problem.

**Comment by jbachorik** [comment] 2015-11-03 12:21
Application log should contain many lines prefixed with "DEBUG:". If it is not, try restarting the application to prune an old BTrace agent. Currently it is not possible to change the debug level on the fly, unfortunately.

**Comment by AbhishekPuligundla** [comment] 2015-11-03 12:37
Even after restarting the application i am getting the same output. Application log doesn't contaion any debug lines and also this error is what i am getting every time start btrace.



ERROR 2015-11-03 12:29:33.051 (ingBeanActionHandler.handleException: 108) Error while calling method CombiTreeFacadeImpl.getLevels().
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.utils.actionhandlers.SpringBeanActionHandler.perform(SpringBeanActionHandler.java:45)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.utils.actionhandlers.ActionHandlerActivator.reflectionInvokeMethod(ActionHandlerActivator.java:108)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.utils.actionhandlers.ActionHandlerActivator.activate(ActionHandlerActivator.java:42)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.utils.actionhandlers.ActionHandlerDispatcher.dispatch(ActionHandlerDispatcher.java:38)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.servlets.Controller$1.doInTransaction(Controller.java:423)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:131)
	at com.digifuel.serviceflow.infra.common.tx.TransactionCRUDTemplate.doExecute(TransactionCRUDTemplate.java:52)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.servlets.Controller.perform(Controller.java:419)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.servlets.Controller.performTask(Controller.java:280)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.servlets.Controller.doPost(Controller.java:127)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.filters.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.VerifyError: (class: com/digifuel/serviceflow/infra/common/trees/facade/CombiTreeFacadeImpl$$FastClassBySpringCGLIB$$42335cbb, method: <init> signature: (Ljava/lang/Class;)V) Register 0 contains wrong type
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:386)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
	at org.springframework.cglib.reflect.FastClass$Generator.create(FastClass.java:64)
	at org.springframework.cglib.proxy.MethodProxy.helper(MethodProxy.java:121)
	at org.springframework.cglib.proxy.MethodProxy.init(MethodProxy.java:74)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:202)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:700)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at com.digifuel.serviceflow.infra.common.validation.ValidationInterceptor.invoke(ValidationInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
	at com.digifuel.serviceflow.infra.common.trees.facade.CombiTreeFacadeImpl$$EnhancerBySpringCGLIB$$de58e253.getLevels(<generated>)
	... 39 more
ERROR 2015-11-03 12:29:33.058 (Controller          .perform        : 436) Failed to execute the transaction
org.springframework.transaction.UnexpectedRollbackException: JTA transaction unexpectedly rolled back (maybe due to a timeout); nested exception is javax.transaction.RollbackException: Transaction set to rollback only
	at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1015)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:148)
	at com.digifuel.serviceflow.infra.common.tx.TransactionCRUDTemplate.doExecute(TransactionCRUDTemplate.java:52)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.servlets.Controller.perform(Controller.java:419)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.servlets.Controller.performTask(Controller.java:280)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.servlets.Controller.doPost(Controller.java:127)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.digifuel.serviceflow.infra.frontoffice.common.web.filters.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.transaction.RollbackException: Transaction set to rollback only
	at com.atomikos.icatch.jta.TransactionImp.rethrowAsJtaRollbackException(TransactionImp.java:70)
	at com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:250)
	at com.atomikos.icatch.jta.TransactionManagerImp.commit(TransactionManagerImp.java:498)
	at com.atomikos.icatch.jta.UserTransactionImp.commit(UserTransactionImp.java:129)
	at org.springframework.transaction.jta.JtaTransactionManager.doCommit(JtaTransactionManager.java:1012)
	... 32 more
Caused by: com.atomikos.icatch.RollbackException: Transaction set to rollback only
	at com.atomikos.icatch.imp.TxRollbackOnlyStateHandler.commit(TxRollbackOnlyStateHandler.java:84)
	at com.atomikos.icatch.imp.CompositeTransactionImp.doCommit(CompositeTransactionImp.java:319)
	at com.atomikos.icatch.imp.CompositeTerminatorImp.commit(CompositeTerminatorImp.java:79)
	at com.atomikos.icatch.jta.TransactionImp.commit(TransactionImp.java:236)
	... 35 more

**Comment by jbachorik** [comment] 2015-11-03 12:54
Normally, you should have something like this in your application log:
```
btrace DEBUG: debugMode is true
btrace DEBUG: unsafeMode is false
btrace DEBUG: dumpClasses is false
btrace DEBUG: probe descriptor path is .
btrace DEBUG: parsed command line arguments
btrace DEBUG: Bootstrap ClassPath: .
btrace DEBUG: ignoring boot classpath element '.' - only jar files allowed
btrace DEBUG: System ClassPath: /opt/java/64bit/jdk1.8.0_40/jre/../lib/tools.jar
btrace DEBUG: stdout is false
btrace DEBUG: starting agent thread
btrace DEBUG: starting server at 2020
btrace DEBUG: waiting for clients
btrace DEBUG: client accepted Socket[addr=/127.0.0.1,port=49198,localport=2020]
btrace DEBUG: got instrument command
btrace DEBUG: verifying BTrace class
btrace DEBUG: verified 'Trace' successfully
btrace DEBUG: created class filter
btrace DEBUG: preprocessing BTrace class Trace
btrace DEBUG: preprocessed BTrace class Trace
btrace DEBUG: creating BTraceRuntime instance for Trace
btrace DEBUG: created BTraceRuntime instance for Trace
btrace DEBUG: removing @OnMethod, @OnProbe methods
btrace DEBUG: removed @OnMethod, @OnProbe methods
btrace DEBUG: sending Okay command
btrace DEBUG: client Trace: got com.sun.btrace.comm.OkayCommand@3fd030f7
btrace DEBUG: about to defineClass Trace
btrace DEBUG: defineClass succeeded for Trace
btrace DEBUG: starting client command handler thread
btrace DEBUG: new Client created com.sun.btrace.agent.RemoteClient@5617e729
btrace DEBUG: filtering loaded classes
...
btrace DEBUG: added as ClassFileTransformer
...
btrace DEBUG: calling retransformClasses (1 classes to be retransformed)
...
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/BTraceUtils$Strings
...
btrace DEBUG: client Trace: instrumenting SecondClass
...
btrace DEBUG: waiting for clients
btrace DEBUG: client Trace: got com.sun.btrace.comm.OkayCommand@2f7f9bcc
```

Verification errors caused by BTrace instrumentation should not prevent these debug messages to be written to the log file. Also, the instrumented classes should be properly written to the provided location. This seems like some interference between Spring AOP and BTrace but without the instrumented classes to inspect it is really difficult to tell what is going on.

**Comment by AbhishekPuligundla** [comment] 2015-11-05 05:27
do you know how to prune the old btrace agent without restarting the application. Also do you think that database connection in the application is creating any problems while using btrace.

**Comment by jbachorik** [comment] 2015-11-05 08:22
Unfortunately, it is not possible to prune the btrace agent from a running application. In general, it is not possible to unload a JVM agent after it has been loaded. However, BTrace agent might be improved to enable changing eg. the verbosity or debugging levels even after it has been started.

For the second part of your question - I don't think the database connection is the culprit here. What could be seen in the previous info was that each transaction was rolled back due to the verification errors of the Spring dynamic proxies instrumented by BTrace.

**Comment by AbhishekPuligundla** [comment] 2015-11-10 06:41
Is it possible to revoke the state of the application after using the btrace. I mean can we keep the backup of the application state and revoke to that state when the tracing is completed. If Thats possible then we can unload the jvm agent without restarting the application.

**Comment by jbachorik** [comment] 2015-11-10 07:43
No, unfortunately, it is not supported by the Attach API in JVM. Once you load an agent it stays loaded. 
We are loading the BTrace agent just once - the subsequent attempts to trace an application will check for the agent being loaded and if it is they will reuse it.

From the log snippet it is not really possible to tell why BTrace stops - one of the possible reasons might be that the instrumentation is very complex and it will take long time to retransform all the affected classes. Other possibility is hitting the permgen limit (if you are running on JDK 7). Let me test this locally and I will get back to you.

**Comment by AbhishekPuligundla** [comment] 2015-11-10 12:14
when we are instrumenting a spring based applications, how will btrace instruments the application. will it use the spring framework instrumentation process or will it use the instrumentation process of the system java.

**Comment by jbachorik** [comment] 2015-11-10 12:36
BTrace does not know anything about Spring specific instrumentation. It is using JVM agent and registers itself as a class transformer (I suspect Spring does something similar).

**Comment by AbhishekPuligundla** [comment] 2015-11-12 11:09
does btrace create any proxy while injecting the trace code to the application. if so will it be similar or different from the proxy created by a spring application (or) the proxy created by spring is modified by the btrace or vice versa is happening.

**Comment by jbachorik** [comment] 2015-11-12 11:54
No, BTrace directly modifies the bytecode of the affected methods.

**Comment by AbhishekPuligundla** [comment] 2015-11-12 12:33
is there a way to avoid a class from tracing that is

if i have a trace script like this
@OnMethod(clazz="/package1.package2.*/",method="/.*/",location=@Location(value=Kind.ENTRY))

but i don't want the btrace to trace some classes that are under package1.package2.*
if there are classes named class1,class2,class3 and class4 are present under package1.package2 then how to avoid tracing class2 and class4. Is there a way to trace only class1 and class3 by using the above line.

**Comment by jbachorik** [comment] 2015-11-12 13:46
Since `clazz="/<regular expression>/"` you are free to put there any regular expression and build rather sophisticated filters. The same goes for the `method=/.../`. Note the opening and closing __/__ which designates the attribute value as a regular expression.

**Comment by AbhishekPuligundla** [comment] 2015-11-13 08:00
i am confused how can i represent a conditional expression in the clazz="/ /"

**Comment by jbachorik** [comment] 2015-11-13 08:20
Read about regular expressions - http://www.regular-expressions.info/
Google is your friend.

**Comment by AbhishekPuligundla** [comment] 2015-11-20 04:30
can you check whether btrace is capable of tracing enterprise java applications which uses spring framework.

**Comment by jbachorik** [comment] 2015-12-12 13:44
If anybody is using BTrace to instrument a Spring based application it would be nice if you could chime in here.

**Comment by jbachorik** [comment] 2016-04-13 17:27
Closing due to inactivity and irreproducibility.

**Closed by jbachorik** 2016-04-13 17:27 UTC
Labels: BTRACE, help wanted, incomplete, question
