### ISSUE TITLE
Problems tracing application server

### ISSUE THREAD

**Issue by cpiment** [btraceio/btrace#231] opened 2016-06-17 05:50 UTC
Hi,

I'm trying to use BTrace to trace a Java EE Application Server, and it works fine when the classes I'm tracing are only instanced once, but when I try to trace a class that has been instanced by different ClassLoaders of differente Web Applications, I get this error in the Application Server Log:

> btrace DEBUG: retransforming loaded classes
> btrace DEBUG: filtering loaded classes
> btrace DEBUG: candidate class org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter added
> btrace DEBUG: candidate class org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter added
> btrace DEBUG: candidate class org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter added
> btrace DEBUG: candidate class org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter added
> btrace DEBUG: candidate class org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter added
> btrace DEBUG: candidate class weblogic.servlet.internal.session.CoherenceWebSessionData added
> btrace DEBUG: candidate class weblogic.servlet.internal.RequestEventsFilter added
> btrace DEBUG: client CoherenceInvalidations$7: got com.sun.btrace.comm.RetransformationStartNotification@240cb732
> btrace DEBUG: calling retransformClasses (7 classes to be retransformed)
> btrace DEBUG: transformed class org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter
> btrace DEBUG: java.util.concurrent.ExecutionException: java.lang.InternalError
> java.util.concurrent.ExecutionException: java.lang.InternalError
> at java.util.concurrent.FutureTask.report(FutureTask.java:122)
> at java.util.concurrent.FutureTask.get(FutureTask.java:192)
> at com.sun.btrace.agent.Main.startServer(Main.java:487)
> at com.sun.btrace.agent.Main.access$000(Main.java:58)
> at com.sun.btrace.agent.Main$2.run(Main.java:119)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.InternalError
> at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
> at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
> at com.sun.btrace.agent.Client.retransformLoaded(Client.java:383)
> at com.sun.btrace.agent.Main$3.run(Main.java:506)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> ... 1 more

Do you know why does this happen?

**Comment by jbachorik** [comment] 2016-06-25 10:57
Try running the btrace agent with `dumpClasses=true,dumpDir=<dest_folder>` to get the transformed class files and store them in <dest_folder>. You can then attach the files to this issue so I can inspect whether there are any problems with the instrumentation.

Although, from the first glance it looks like instrumentation conflict between BTrace and WebLogic AOP.

Waiting for the class files.

**Comment by cpiment** [comment] 2016-06-27 07:49
[instrumented.tar.gz](https://github.com/btraceio/btrace/files/334317/instrumented.tar.gz)

Hi,

I have dumped the classes, see attached file.

Thanks for your help

**Comment by jbachorik** [comment] 2016-07-01 13:04
The archive does not seem to contain the Spring classes - you need to run your application till the point you see the BTrace exception because the classes are loaded and instrumented on demand.

**Comment by cpiment** [comment] 2016-07-18 09:41
I have just run the application to the point where it runs the Spring code, but it does not dump the classes. Do I have to start the App Server with any arguments? Or just starting the Btrace client with "dumpDir=/var/tmp/dump" should be enough?

**Comment by jbachorik** [comment] 2016-07-18 09:51
You can use `btrace -v -d <path> ... ` to enable dumping of the
instrumented classes as well as get the full debug output which you can
also attach to this issue.

**Comment by cpiment** [comment] 2016-07-18 10:10
I already did that, but that did not produce the dump. The log of the agent. I'm attaching the btrace client and server logs.
[agent_log.txt](https://github.com/btraceio/btrace/files/368718/agent_log.txt)
[server_log.txt](https://github.com/btraceio/btrace/files/368719/server_log.txt)

**Comment by jbachorik** [comment] 2016-07-18 10:28
Ok, the server log sheds some more light on what is going on. The class
retransformation process crashes before actually going back to BTrace code
and inserting the BTrace instrumentation. It might be crashing in the code
deciding what to instrument but, unfortunately, there is no indication what
would be the reason of this crash.

Is this a weblogic server? Could you do the last experiment and use a
BTrace script where @OnMethod declaration would not match any available
classes? Just to see whether the problem is somewhere in the BTrace
internals or it is retransforming certain classes (even without any
modifications) that are causing this problem?

Any chance you could provide a small reproducer?

Thanks!

-JB-

**Comment by cpiment** [comment] 2016-07-18 11:06
I have just tested a trace script with a fake class in the @OnMethod declaration. Now there is no crash in the agent or server logs, I attach the logs and the BTrace script.

I cannot provide a reproducer right now, but I will try to provide it to you ASAP.

Regards

[server_log_nonmatch.txt](https://github.com/btraceio/btrace/files/368850/server_log_nonmatch.txt)
[agent_log_nonmatch.txt](https://github.com/btraceio/btrace/files/368849/agent_log_nonmatch.txt)
[NonMatch.java.txt](https://github.com/btraceio/btrace/files/368852/NonMatch.java.txt)

**Comment by yardus** [comment] 2016-07-18 11:07
Thanks. I will take a loot at the possibility of adding more logging to the instrumentation process.

**Comment by jbachorik** [comment] 2016-12-30 21:12
I have added logging to provide some insight which classes are queued to be retransformed. Could you try with the trunk version of BTrace to see the logs?

**Comment by cpiment** [comment] 2017-01-04 15:16
Now it doesn't crash, but some classes get skipped during retransformation. I'm attaching the logs and the dumped transformed classes. I have test with a clone of the repo made and built today.

[20170104dumpedclasses.tar.gz](https://github.com/btraceio/btrace/files/685026/20170104dumpedclasses.tar.gz)
[20170104server_log.txt](https://github.com/btraceio/btrace/files/685027/20170104server_log.txt)
[20170104agent_log.txt](https://github.com/btraceio/btrace/files/685028/20170104agent_log.txt)

**Comment by jbachorik** [comment] 2017-01-05 15:30
As for the skipped class `com.telefonica.coco.lib.security.preauth.filter.TelcoPreAuthenticationFilter`, please, make sure that the intercepted method `doGetPrincipal` is actually defined in this class directly. If the method is just inherited its bytecode will be in a parent class and therefore there would be nothing to instrument.

**Comment by jbachorik** [comment] 2017-01-10 16:43
Most probably resolved by #240 - closing.
If you still can reproduce the problem, feel free reopening.

**Closed by jbachorik** 2017-01-10 16:43 UTC
Labels: BTRACE, bug, Core, help wanted

**Comment by Tapan2609** [comment] 2018-01-19 10:53
Hi @jbachorik
How to instrument application classes when there are multiple deployments in weblogic. If we specify weblogic's PID, It will instrument only weblogic internal classes. Is it possible to attach btrace to a single deployment in a weblogic server?
