### ISSUE TITLE
btrace verification error

### ISSUE THREAD

**Issue by jacky1982** [btraceio/btrace#316] opened 2018-01-28 04:24 UTC
btrace DEBUG: calling retransformClasses (1 classes to be retransformed)
btrace DEBUG: Attempting to retransform class: org.apache.hadoop.hdfs.server.namenode.LeaseManager$Monitor
btrace DEBUG: transformed class org.apache.hadoop.hdfs.server.namenode.LeaseManager$Monitor
btrace DEBUG: verification error: org.apache.hadoop.hdfs.server.namenode.LeaseManager$Monitor

btrace script :

import com.sun.btrace.BTraceUtils;
import com.sun.btrace.annotations.BTrace;
import com.sun.btrace.annotations.Kind;
import com.sun.btrace.annotations.Location;
import com.sun.btrace.annotations.OnMethod;
import com.sun.btrace.annotations.ProbeClassName;
import com.sun.btrace.annotations.ProbeMethodName;
@BTrace(trusted=true)
public class LockTrace {
	@OnMethod(clazz = "org.apache.hadoop.hdfs.server.namenode.LeaseManager$Monitor", location = @Location(value = Kind.LINE, line = -1))
	public static void online(@ProbeClassName String pcn, @ProbeMethodName String pmn, int line) {
		BTraceUtils.print(line);
	}
}

DEBUG: attaching to 7481
DEBUG: checking port availability: 2020
DEBUG: attached to 7481
DEBUG: loading /opt/btrace-bin-1.3.10/build/btrace-agent.jar
DEBUG: agent args: port=2020,statsd=,debug=true,trusted=true,bootClassPath=.,systemClassPath=/usr/java/jdk1.7.0_80/lib/tools.jar,probeDescPath=.
DEBUG: loaded /opt/btrace-bin-1.3.10/build/btrace-agent.jar
DEBUG: registering shutdown hook
DEBUG: registering signal handler for SIGINT
DEBUG: submitting the BTrace program
DEBUG: opening socket to 2020
DEBUG: setting up client settings
DEBUG: sending instrument command
DEBUG: entering into command loop
DEBUG: received com.sun.btrace.comm.OkayCommand@4979b3e6
DEBUG: received com.sun.btrace.comm.RetransformationStartNotification@a42a751
DEBUG: received com.sun.btrace.comm.OkayCommand@31b75e54

**Comment by jbachorik** [comment] 2018-02-17 15:08
Please, try version 1.3.10.2 - a few bugs caused by the new stackframe map calculator were fixed since 1.3.10 there and it is very probable that this verification error will not occur any more.

**Comment by jbachorik** [comment] 2018-03-18 16:36
Ping. Can you reproduce this error with version 1.3.10.2?
If I don't hear from you in next 7 days I will close this issue.

**Closed** 2018-04-01 15:50 UTC
