### ISSUE TITLE
JDWP conflict 

### ISSUE THREAD

**Issue by chgitcrazy** [btraceio/btrace#391] opened 2019-08-01 10:35 UTC
When I start remote debug java application with VM parameter "agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8787" and set breakpoint,
then I start btrace , it occured "CORE DUMP".
Error as follows:

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007fc80bfdebe3, pid=14344, tid=140496657504000

 JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 V  [libjvm.so+0x77cbe3]  JvmtiEnv::GetClassMethods(oopDesc*, int*, _jmethodID***)+0x2f3

 Core dump written. Default location: /home/test/core or core.14344 (max size 4194304 kB). To ensure a full core dump, try "ulimit -c unlimited" before starting Java again

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

---------------  T H R E A D  ---------------

Current thread (0x00007fc8041e8800):  JavaThread "JDWP Transport Listener: dt_socket" daemon [_thread_in_vm, id=14355, stack(0x00007fc7ed54d000,0x00007fc7ed5ce000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00007fc6e77cdaf0

0x00007f668993a4f5 in raise () from /lib64/libc.so.6
1  0x00007f668993bcd5 in abort () from /lib64/libc.so.6
2  0x00007f668924f6b5 in os::abort(bool) () from /usr/local/jdk1.8.0_45/jre/lib/amd64/server/libjvm.so
3  0x00007f66893ecda3 in VMError::report_and_die() () from /usr/local/jdk1.8.0_45/jre/lib/amd64/server/libjvm.so
4  0x00007f6689254bdf in JVM_handle_linux_signal () from /usr/local/jdk1.8.0_45/jre/lib/amd64/server/libjvm.so
5  0x00007f668924b493 in signalHandler(int, siginfo*, void*) () from /usr/local/jdk1.8.0_45/jre/lib/amd64/server/libjvm.so
6  <signal handler called>
7  0x00007f66890bcbe3 in JvmtiEnv::GetClassMethods(oopDesc*, int*, _jmethodID***) () from /usr/local/jdk1.8.0_45/jre/lib/amd64/server/libjvm.so
8  0x00007f668906ef40 in jvmti_GetClassMethods () from /usr/local/jdk1.8.0_45/jre/lib/amd64/server/libjvm.so
9  0x00007f6683dcc96e in methods1 () from /usr/local/jdk1.8.0_45/jre/lib/amd64/libjdwp.so
10 0x00007f6683dd79c6 in debugLoop_run () from /usr/local/jdk1.8.0_45/jre/lib/amd64/libjdwp.so
11 0x00007f6683dea991 in acceptThread () from /usr/local/jdk1.8.0_45/jre/lib/amd64/libjdwp.so
12 0x00007f66890d7102 in JvmtiAgentThread::call_start_function() () from /usr/local/jdk1.8.0_45/jre/lib/amd64/server/libjvm.so
13 0x00007f668939c86f in JavaThread::thread_main_inner() () from /usr/local/jdk1.8.0_45/jre/lib/amd64/server/libjvm.so
14 0x00007f668939c99c in JavaThread::run() () from /usr/local/jdk1.8.0_45/jre/lib/amd64/server/libjvm.so
15 0x00007f6689250de8 in java_start(Thread*) () from /usr/local/jdk1.8.0_45/jre/lib/amd64/server/libjvm.so
16 0x00007f668a0bdaa1 in start_thread () from /lib64/libpthread.so.0
17 0x00007f66899f0ced in clone () from /lib64/libc.so.6

**Comment by jbachorik** [comment] 2019-08-01 15:34
This looks pretty much like https://bugs.openjdk.java.net/browse/JDK-8149743

Please, try updating JDK to most recent version (the linked bug was fixed in 8u72)

**Comment by chgitcrazy** [comment] 2019-08-04 01:40
Is there any solution which could bypass this bug in btrace

**Comment by jbachorik** [comment] 2019-08-05 12:13
Unfortunately no. This is a bug in JVMTI - 8u45 is pretty old version and you really should consider moving to 8u72 at least.

**Comment by chgitcrazy** [comment] 2019-08-14 06:16
* <P>
     * The retransformation may change method bodies, the constant pool and attributes.
     * The retransformation must not add, remove or rename fields or methods, change the
     * signatures of methods, or change inheritance.  These restrictions maybe be
     * lifted in future versions.  The class file bytes are not checked, verified and installed
     * until after the transformations have been applied, if the resultant bytes are in
     * error this method will throw an exception.
     *
     * <P>

  This description is from `retransformClasses` API comment ,it seems that add methods is 
  prohibited ?

**Comment by jbachorik** [comment] 2019-08-14 07:10
Adding private static methods has been supported on Hotspot based JVMs. Although it is not in spec and other JVMs may choose not to do that.

**Comment by chgitcrazy** [comment] 2019-08-14 12:12
> Adding private static methods has been supported on Hotspot based JVMs. Although it is not in spec and other JVMs may choose not to do that.
Is this feature supported since some jdk version such as 8u45 or 8u72？

**Comment by jbachorik** [comment] 2020-01-28 01:55
That feature has been supported long before 8u45. The crash mentioned in this issue is caused by a bug in JVMTI impl in 8u45. Please, update to a recent 8u version. Closing.

**Closed by jbachorik** 2020-01-28 01:55 UTC
Labels: jdkbug
