### ISSUE TITLE
Build fails with missing artifact

### ISSUE THREAD

**Issue by magicwerk** [btraceio/btrace#631] opened 2023-06-23 07:18 UTC
Building after git clone fails with the following error:

./gradlew :btrace-dist:build

* What went wrong:
A problem occurred configuring project ':btrace-client'.
> Could not resolve all files for configuration ':btrace-client:classpath'.
   > Could not find org.ajoberstar.grgit:grgit-core:4.0.1.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :btrace-client > net.nemerosa.versioning:net.nemerosa.versioning.gradle.plugin:2.15.1 > gradle.plugin.net.nemerosa:versioning:2.15.1

To build successfully, I updated the version in settings.gradle:

//            plugin ('versioning', 'net.nemerosa.versioning').version('2.15.1')
            plugin ('versioning', 'net.nemerosa.versioning').version('3.0.0')

**Comment by jbachorik** [comment] 2023-06-25 19:51
Hi,
Thanks for reporting!
Unfortunately, I can not reproduce - I tried a clean checkout but it still builds.
Anyway, I opened a PR to bump the plugin version, just in case.

**Comment by jbachorik** [comment] 2023-06-25 20:05
As it turns out, the '3.0.0' version does not support Java 8 any more.
The missing version of 'grgit-core' should still be available in [jcenter repo ](https://mvnrepository.com/artifact/org.ajoberstar.grgit/grgit-core?repo=jcenter) so I modified the PR to explicitly declare that repository usage. Could you try that branch and see if it would resolve your issue ? (I still can't reproduce ...)

**Comment by magicwerk** [comment] 2023-06-26 12:43
That's interesting, that's exactly what I tried as well when the build failed on my side, but I still to a strange Nginx error then...
So it was probably a temporary infrastructure hickup which has been resolved now.
Anyhow, if I rerun the build right on develop branch (i.e. without the fix adding jcenter), it works fine - if you look at the output below, it seems the redirect is done automatically by the maven repo and no change seems to be needed.

```
2023-06-26T14:30:02.041+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Resolve grgit-core-4.0.1.jar (org.ajoberstar.grgit:grgit-core:4.0.1)' started
2023-06-26T14:30:02.051+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Download https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar' started
2023-06-26T14:30:02.886+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Download https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar'
2023-06-26T14:30:02.888+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Resolve grgit-core-4.0.1.jar (org.ajoberstar.grgit:grgit-core:4.0.1)'
2023-06-26T14:30:02.888+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Resolve grgit-core-4.0.1.jar (org.ajoberstar.grgit:grgit-core:4.0.1)' completed
2023-06-26T14:30:01.968+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for org.ajoberstar.grgit:grgit-core:4.0.1 using repositories [Gradle Central Plugin Repository]
2023-06-26T14:30:01.968+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'org.ajoberstar.grgit:grgit-core:4.0.1' in 'Gradle Central Plugin Repository'
2023-06-26T14:30:01.968+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Using org.ajoberstar.grgit:grgit-core:4.0.1 from Maven repository 'Gradle Central Plugin Repository'
2023-06-26T14:30:01.968+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder] Visiting configuration org.ajoberstar.grgit:grgit-core:4.0.1(runtime).
2023-06-26T14:30:02.000+0200 [DEBUG] [org.gradle.internal.component.model.LoggingAttributeMatchingExplanationBuilder] Selected match org.ajoberstar.grgit:grgit-core:4.0.1 configuration runtime from candidates [org.ajoberstar.grgit:grgit-core:4.0.1 configuration runtime] for {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=8.1.1, org.gradle.usage=java-runtime}
2023-06-26T14:30:02.042+0200 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar
2023-06-26T14:30:02.042+0200 [DEBUG] [org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor] Constructing external resource: https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar
2023-06-26T14:30:02.051+0200 [DEBUG] [org.gradle.internal.resource.transport.http.HttpResourceAccessor] Constructing external resource: https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar
2023-06-26T14:30:02.051+0200 [DEBUG] [org.gradle.internal.resource.transport.http.HttpClientHelper] Performing HTTP GET: https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar
2023-06-26T14:30:02.092+0200 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Executing request GET /m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar HTTP/1.1
2023-06-26T14:30:02.495+0200 [DEBUG] [org.gradle.internal.resource.transport.http.AlwaysFollowAndPreserveMethodRedirectStrategy] Redirect requested to location 'https://jcenter.bintray.com/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar'
2023-06-26T14:30:02.495+0200 [DEBUG] [org.apache.http.impl.execchain.RedirectExec] Redirecting to 'https://jcenter.bintray.com/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar' via {s}->https://jcenter.bintray.com:443
2023-06-26T14:30:02.572+0200 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Executing request GET /org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar HTTP/1.1
2023-06-26T14:30:02.733+0200 [DEBUG] [org.gradle.internal.resource.transport.http.HttpResponseResource] Attempting to download resource https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar.
2023-06-26T14:30:02.733+0200 [INFO] [org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor] Downloading https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar to /home/ubuntu/.gradle/.tmp/gradle_download7225960169490676614bin
2023-06-26T14:30:02.886+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Download https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.jar' completed
2023-06-26T14:30:02.888+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Downloaded artifact 'grgit-core-4.0.1.jar (org.ajoberstar.grgit:grgit-core:4.0.1)' from resolver: Gradle Central Plugin Repository
2023-06-26T14:30:02.973+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for org.ajoberstar.grgit:grgit-core:4.0.1 using repositories [Gradle Central Plugin Repository]
2023-06-26T14:30:02.973+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'org.ajoberstar.grgit:grgit-core:4.0.1' in 'Gradle Central Plugin Repository'
2023-06-26T14:30:02.973+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Using org.ajoberstar.grgit:grgit-core:4.0.1 from Maven repository 'Gradle Central Plugin Repository'
2023-06-26T14:30:02.973+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder] Visiting configuration org.ajoberstar.grgit:grgit-core:4.0.1(runtime).
2023-06-26T14:30:02.977+0200 [DEBUG] [org.gradle.internal.component.model.LoggingAttributeMatchingExplanationBuilder] Selected match org.ajoberstar.grgit:grgit-core:4.0.1 configuration runtime from candidates [org.ajoberstar.grgit:grgit-core:4.0.1 configuration runtime] for {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=8.1.1, org.gradle.usage=java-runtime}
2023-06-26T14:30:03.335+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for org.ajoberstar.grgit:grgit-core:4.0.1 using repositories [Gradle Central Plugin Repository]
2023-06-26T14:30:03.335+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'org.ajoberstar.grgit:grgit-core:4.0.1' in 'Gradle Central Plugin Repository'
2023-06-26T14:30:03.335+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Using org.ajoberstar.grgit:grgit-core:4.0.1 from Maven repository 'Gradle Central Plugin Repository'
2023-06-26T14:30:03.335+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder] Visiting configuration org.ajoberstar.grgit:grgit-core:4.0.1(runtime).
2023-06-26T14:30:03.339+0200 [DEBUG] [org.gradle.internal.component.model.LoggingAttributeMatchingExplanationBuilder] Selected match org.ajoberstar.grgit:grgit-core:4.0.1 configuration runtime from candidates [org.ajoberstar.grgit:grgit-core:4.0.1 configuration runtime] for {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=8.1.1, org.gradle.usage=java-runtime}
```

**Comment by jbachorik** [comment] 2023-07-08 16:52
Thanks for verifying!
I assume it is ok to close the issue now.

**Closed by jbachorik** 2023-07-08 16:52 UTC
