### ISSUE TITLE
Sample AllCalls3 does not work with primitive parameter

### ISSUE THREAD

**Issue by ymmihw** [btraceio/btrace#229] opened 2016-06-13 08:28 UTC
BTrace v.1.3.7 (20160509)

code to trace

```
    public static void add(String s,
            int i) {
        // System.out.println(11); if uncomment this, btrace will not work
        "abcd".equalsIgnoreCase("abc");
        Integer.parseInt("123");
    }
```

**Comment by jbachorik** [comment] 2016-06-25 12:18
Looks like a duplicate of #228 - tried to reproduce after fixing that issue and everything seems to be working just fine.

**Closed by jbachorik** 2016-06-25 12:18 UTC
