### ISSUE TITLE
[shell bug] 'jre' directory test faild

### ISSUE THREAD

**Issue by wxlfight** [btraceio/btrace#407] opened 2020-03-10 08:31 UTC
**when i run the btrace command, then errors come out like:**

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/source/util/TaskListener
        at org.openjdk.btrace.compiler.Compiler.<init>(Compiler.java:70)
        at org.openjdk.btrace.compiler.Compiler.<init>(Compiler.java:74)
        at org.openjdk.btrace.client.Client.compile(Client.java:204)
        at org.openjdk.btrace.client.Client.compile(Client.java:187)
        at org.openjdk.btrace.client.Main.main(Main.java:195)

Caused by: java.lang.ClassNotFoundException: com.sun.source.util.TaskListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 5 more

**Obviously, tools.jar not load successfully which contain class 'com.sun.source.util.TaskListener'.
when i check the shell script 'btrace', i found this:**
`
if [ -f "${JAVA_HOME}/jre" ]; then ...
`
**Since 'jre' is a directory, so '-f "${JAVA_HOME}/jre" ' will be false, which is the reason why 'TOOLS_JAR' is empty, to correct this use '-d "${JAVA_HOME}/jre" '.**

**btw, i don't understand why we test if 'jre' is exist?**

**Comment by jbachorik** [comment] 2020-03-10 09:21
Thanks for reporting!
This is a duplicate of #405

**Closed by jbachorik** 2020-03-10 09:21 UTC
Labels: duplicate
