### ISSUE TITLE
Invoking methods on injected services is causing verification error

### ISSUE THREAD

**Issue by yashk** [btraceio/btrace#256] opened 2016-12-08 13:04 UTC
i am trying to run example mentioned http://btraceio.github.io/btrace/2015/02/statsd-integration/

btrace-1.3.8.3 version , is this really supported or just proposal. i am getting following error for trace
class
```
package com.sun.btrace.samples;

import com.sun.btrace.BTraceUtils;
import com.sun.btrace.Profiler;
import com.sun.btrace.annotations.*;
import com.sun.btrace.services.impl.Statsd;

@BTrace class ProfilingAM {
    @Injected(factoryMethod = "getInstance") private  Statsd sd;

    @Property
    Profiler swingProfiler = BTraceUtils.Profiling.newProfiler();
    
    @OnMethod(clazz="Test", method="doStuff")
    void entry(@ProbeMethodName(fqn=true) String probeMethod) { 
        BTraceUtils.Profiling.recordEntry(swingProfiler, probeMethod);
    }
    
    @OnMethod(clazz="Test", method="doStuff", location=@Location(value=Kind.RETURN))
    void exit(@ProbeMethodName(fqn=true) String probeMethod, @Duration long duration) { 
        BTraceUtils.Profiling.recordExit(swingProfiler, probeMethod, duration);
        sd.increment("my.metric.b", "regular,distribution:gaussian");
    }
    
    @OnTimer(5000)
    void timer() {
        BTraceUtils.Profiling.printSnapshot("AM performance profile", swingProfiler);
    }
}
``` 

```
java -javaagent:./build/btrace-agent.jar=script=./com/sun/btrace/samples/ProfilingAM.class,noServer=true,debug=true,statsd=localhost:8125,stdout=true Test
```

Error

```
> ~/software/btrace-bin-1.3.8.3  java -javaagent:./build/btrace-agent.jar=script=./com/sun/btrace/samples/ProfilingAM.class,noServer=true,debug=true,statsd=localhost:8125,stdout=true Test
objc[6726]: Class JavaLaunchHelper is implemented in both /Users/ykochare/.jenv/versions/1.8/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
btrace DEBUG: debugMode is true
btrace DEBUG: startupRetransform is true
btrace DEBUG: dumpClasses is false
btrace DEBUG: unsafeMode is false
btrace DEBUG: probe descriptor path is .
btrace DEBUG: stdout is true
btrace DEBUG: initial script is ./com/sun/btrace/samples/ProfilingAM.class
btrace DEBUG: loading BTrace class
### BTrace Log: 12/8/16 6:33 PM

btrace DEBUG: verifying BTrace class ...
btrace DEBUG: com.sun.btrace.samples.ProfilingAM failed verification
btrace DEBUG: com.sun.btrace.VerifierException: method calls are not allowed - only calls to BTraceUtils are allowed: com/sun/btrace/services/impl/Statsd.increment(Ljava/lang/String;Ljava/lang/String;)V
com.sun.btrace.VerifierException: method calls are not allowed - only calls to BTraceUtils are allowed: com/sun/btrace/services/impl/Statsd.increment(Ljava/lang/String;Ljava/lang/String;)V
	at com.sun.btrace.runtime.Verifier.reportError(Verifier.java:204)
	at com.sun.btrace.runtime.MethodVerifier.visitMethodInsn(MethodVerifier.java:194)
	at com.sun.btrace.org.objectweb.asm.ClassReader.a(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.b(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.sun.btrace.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.sun.btrace.runtime.BTraceProbe.initialize(BTraceProbe.java:406)
	at com.sun.btrace.runtime.BTraceProbe.initialize(BTraceProbe.java:393)
	at com.sun.btrace.runtime.BTraceProbe.<init>(BTraceProbe.java:93)
	at com.sun.btrace.runtime.BTraceProbeFactory.createProbe(BTraceProbeFactory.java:50)
	at com.sun.btrace.agent.Client.load(Client.java:365)
	at com.sun.btrace.agent.Client.loadClass(Client.java:228)
	at com.sun.btrace.agent.FileClient.init(FileClient.java:55)
	at com.sun.btrace.agent.FileClient.<init>(FileClient.java:50)
	at com.sun.btrace.agent.FileClient.<init>(FileClient.java:62)
	at com.sun.btrace.agent.Main.loadBTraceScript(Main.java:457)
	at com.sun.btrace.agent.Main.startScripts(Main.java:203)
	at com.sun.btrace.agent.Main.main(Main.java:104)
	at com.sun.btrace.agent.Main.premain(Main.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
btrace DEBUG: sending error command
btrace DEBUG: client com.sun.btrace.samples.ProfilingAM: got com.sun.btrace.comm.ErrorCommand@c4437c4
btrace DEBUG: sending exit command
btrace DEBUG: client com.sun.btrace.samples.ProfilingAM: got com.sun.btrace.comm.ExitCommand@433c675d
btrace DEBUG: onExit:
btrace DEBUG: cleaning up transformers
btrace DEBUG: removing instrumentation
btrace DEBUG: retransforming loaded classes
btrace DEBUG: filtering loaded classes
! ERROR
```

**Comment by jbachorik** [comment] 2016-12-08 17:16
That should work. Let me see what is going on ...

**Comment by yashk** [comment] 2016-12-11 13:32
@jbachorik  did you get chance to look at this issue ?, i am trying to  use btrace to instrument hadoop MR jobs and statsd feature is required collect trace data at central location.

**Comment by jbachorik** [comment] 2016-12-12 09:23
Sorry, I'm pretty busy right now. I should be able to take a look by the
end of this week. Till then you can switch the script to 'unsafe' mode to
allow statsd calls.

**Comment by yashk** [comment] 2016-12-14 14:41
@jbachorik 
i tried this again with your latest commit , built btrace from source. Same Trace file as above now getting error

```
ERROR
java.lang.IllegalAccessError: tried to access method com.sun.btrace.services.impl.Statsd.<init>()V from class Test
```
Details logs below

```
$ bin/btrace --version
BTrace v.1.4-SNAPSHOT (20161214)
```
```
$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```
```
$ bin/btracec samples/ProfilingAM.java
*** field annotation: Lcom/sun/btrace/annotations/Injected;
*** field annotation: Lcom/sun/btrace/annotations/Property;
```

```
public class Test{
	public java.util.Random r = new java.util.Random(System.currentTimeMillis());
	public static void main(String[] args) throws Exception {

		Thread t = new Thread(new Runnable(){
			public void run(){
				Test test = new Test();
				try{while(true)test.doStuff();}catch(Exception e){};
			}
		});

		t.start();
		t.join();

		
	}

	public void doStuff() throws Exception{
		Thread.sleep(r.nextInt(2000));
		System.out.print(".");
	}
}
```

```
$ ls -lrt Test*
-rw-r--r--@ 1 yash  staff  453 Dec 14 19:54 Test.java
-rw-r--r--  1 yash  staff  883 Dec 14 20:05 Test.class
-rw-r--r--  1 yash  staff  483 Dec 14 20:05 Test$1.class
```

```
java -javaagent:./build/btrace-agent.jar=script=./com/sun/btrace/samples/ProfilingAM.class,noServer=true,debug=true,statsd=localhost:8125,stdout=true Test
```


```
objc[48189]: Class JavaLaunchHelper is implemented in both /Users/yash/.jenv/versions/1.8/bin/java (0x10cb004c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10cbc84e0). One of the two will be used. Which one is undefined.
btrace DEBUG: debugMode is true
btrace DEBUG: startupRetransform is true
btrace DEBUG: dumpClasses is false
btrace DEBUG: unsafeMode is true
btrace DEBUG: probe descriptor path is .
btrace DEBUG: stdout is true
btrace DEBUG: initial script is ./com/sun/btrace/samples/ProfilingAM.class
btrace DEBUG: loading BTrace class
### BTrace Log: 12/14/16 8:09 PM

btrace DEBUG: verifying BTrace class ...
btrace DEBUG: BTrace class com.sun.btrace.samples.ProfilingAM verified
btrace DEBUG: preprocessing BTrace class com.sun.btrace.samples.ProfilingAM ...
btrace DEBUG: ... preprocessed
btrace DEBUG: loaded 'com.sun.btrace.samples.ProfilingAM' successfully
btrace DEBUG: creating BTraceRuntime instance for com.sun.btrace.samples.ProfilingAM
btrace DEBUG: created BTraceRuntime instance for com.sun.btrace.samples.ProfilingAM
btrace DEBUG: sending Okay command
btrace DEBUG: client com.sun.btrace.samples.ProfilingAM: got com.sun.btrace.comm.OkayCommand@685f4c2e
btrace DEBUG: about to defineClass com/sun/btrace/samples/ProfilingAM
btrace DEBUG: defineClass succeeded for com/sun/btrace/samples/ProfilingAM
btrace DEBUG: new Client created com.sun.btrace.agent.FileClient@50de8dc0
btrace DEBUG: retransforming loaded classes
btrace DEBUG: filtering loaded classes
btrace DEBUG: noServer is true, server not started
btrace DEBUG: transformed class Test
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/profiling/MethodInvocationRecorder
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/Profiler$Record
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/Profiler$Record$1
btrace DEBUG: client com.sun.btrace.samples.ProfilingAM: got com.sun.btrace.comm.OkayCommand@64f7047
.btrace DEBUG: skipping transform for BTrace class com/sun/btrace/services/impl/Statsd
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/services/spi/SimpleService
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/services/spi/BTraceService
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/ExitException
btrace DEBUG: client com.sun.btrace.samples.ProfilingAM: got com.sun.btrace.comm.ErrorCommand@8889efe
! ERROR
java.lang.IllegalAccessError: tried to access method com.sun.btrace.services.impl.Statsd.<init>()V from class Test
	at Test.$btrace$com$sun$btrace$samples$ProfilingAM$exit(Test.java)
	at Test.doStuff(Test.java:21)
	at Test$1.run(Test.java:8)
	at java.lang.Thread.run(Thread.java:745)
.btrace DEBUG: client com.sun.btrace.samples.ProfilingAM: got com.sun.btrace.comm.ErrorCommand@49b594c5
! ERROR
java.lang.IllegalAccessError: tried to access method com.sun.btrace.services.impl.Statsd.<init>()V from class Test
	at Test.$btrace$com$sun$btrace$samples$ProfilingAM$exit(Test.java)
	at Test.doStuff(Test.java:21)
	at Test$1.run(Test.java:8)
	at java.lang.Thread.run(Thread.java:745)
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/Profiler$Snapshot
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/comm/GridDataCommand
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/comm/DataCommand
.btrace DEBUG: client com.sun.btrace.samples.ProfilingAM: got com.sun.btrace.comm.GridDataCommand@78b61ffc
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/aggregation/HistogramData
AM performance profile
  Block                     Invocations  SelfTime.Total  SelfTime.Avg  SelfTime.Min  SelfTime.Max  WallTime.Total  WallTime.Avg  WallTime.Min  WallTime.Max
  public void Test#doStuff            2      3385954647    1692977323    1402036347    1983918300      3385954647    1692977323    1402036347    1983918300
btrace DEBUG: client com.sun.btrace.samples.ProfilingAM: got com.sun.btrace.comm.ErrorCommand@4c6ccd7e
```

**Comment by yardus** [comment] 2016-12-14 20:54
Hm, this is embarrassing. I tested the change with a simple test script but it obviously missed something. I will use your reproducer to get to the root cause.

**Comment by yashk** [comment] 2016-12-17 18:48
@yardus @jbachorik  any luck on this issue ? let me know if i can help out i would need some guidance in areas of code to look into.

**Comment by jbachorik** [comment] 2016-12-30 17:14
The last issue was due to processing error when dealing with BTrace short syntax. Fixed in https://github.com/btraceio/btrace/commit/b3038b75eb39d3ed7416a9541d5ceff5408ace06

**Closed by jbachorik** 2016-12-30 17:14 UTC
