### ISSUE TITLE
how can I call exit()  in a shell script when I want to terminate the monitoring?

### ISSUE THREAD

**Issue by TheodoreSKong** [btraceio/btrace#537] opened 2022-05-18 09:52 UTC
how can I call exit()  in a shell script when I want to terminate the monitoring?
I START the btrace in a shell scripts with command "btrace PID xx.java" command but I don't know how to terminate it except using kill command..

another question is that can I write some information into different files in the trace scripts? not via the stdout...

**Comment by jbachorik** [comment] 2022-05-19 06:21
Hi @TheodoreSKong 

> I START the btrace in a shell scripts with command "btrace PID xx.java" command but I don't know how to terminate it except using kill command..

Unfortunately, there is no easy way as of now. There is an unattended mode available (https://withent.blogspot.com/2020/12/btrace-update-from-trenches-unattended.html) when you can leave a probe in 'detached' mode and re-attach later but it is still relying on getting the commands from the command menu (when you Ctrl-C the btrace process).
Actually, this would be a nice addition to the unattended mode - allowing to execute a command on a previously detached probe without going through the interactive menu.

> another question is that can I write some information into different files in the trace scripts? not via the stdout...

You can redirect the probe output to a file via `-o <filename>` option but it is at per-probe level.
Why do you need to output data to different files?

**Comment by jbachorik** [comment] 2022-05-20 09:52
Yes, when you kill the application itself the btrace will also shut down.

As for different outputs - right now the easiest way would be to have several tracing scripts because the output files will be created per the tracing script.

**Comment by TheodoreSKong** [comment] 2022-05-20 17:42
I have tried this, but too many probes make the monitored app crash immediately... so it seems work by putting all logs into one file then using reg to separate them

**Comment by jbachorik** [comment] 2022-05-20 18:30
> too many probes make the monitored app crash immediately.

What number of probes are we talking about? TBH, crash is not supposed to happen so if you have some magic number where things start going south I might try reproducing and possibly fixing that issue.

**Comment by TheodoreSKong** [comment] 2022-05-20 18:38
There should be the same number with the packages under org.Apache.Cassandra.xxx ，nearly 30……

**Comment by TheodoreSKong** [comment] 2022-05-20 18:41
[Cassandra 4.0.4](https://www.apache.org/dyn/closer.lua/cassandra/4.0.4/apache-cassandra-4.0.4-bin.tar.gz)  and btreace 2.2.2 I’m used. When I use the all methods scripts, the Cassandra app will become unable to connect and throw noclassdeffound error , so I try to separate them in different probes things become worse and the app crashed

**Comment by jbachorik** [comment] 2022-07-04 20:07
In #559 support for stopping a BTrace probe previously started in unattended mode is added.

**Comment by jbachorik** [comment] 2022-07-12 20:25
Fixed by #559

**Closed by jbachorik** 2022-07-12 20:25 UTC
