### ISSUE TITLE
Exception in thread "main"  java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by scutlxp** [btraceio/btrace#398] opened 2019-11-19 11:43 UTC
I run the btrace script (as follow) to trace target program,  **java.lang.NoSuchMethodError** occurred when I quit the trace.  The btrace version is
**v1.3.11.3 (2018-12-17)**. The complete error is as follows:
```
Exception in thread "main"  java.lang.NoSuchMethodError: TestMain.$btrace$TestBtrace$printTime(Ljava/lang/String;Ljava/lang/String;J)V
at TestMain.print(TestMain.java:12)
at TestMain.main(TestMain.java)
```
The btrace script as follows:
```
@BTrace
public class TestBtrace {
   @OnMethod(
      class = "TestMain",
      method = "/.*/,
      location = @Location(value = Kind.RETURN)
   )
   public static void printTime(@ProbeClassName String pcn, @ProbeMethodName String pmn, @Duration long time) {
      println(pcn + "." + pmn + "runs " + time + " ns");
```
The targe  java program as follows:
```java
public class TestMain{
   public static void main(String[] args) throws InterruptedException {
      while(true) {
         printString();
      }
   }
   private static void printString() throws InterruptedException {
      TimeUnit.SECONDS.sleep(1);
      System.out.println("hello world");
   }
}
```

**Comment by jbachorik** [comment] 2020-01-12 18:02
Duplicate of #344

**Closed** 2020-02-11 23:51 UTC
Labels: duplicate
